version: '3'
services:

  web:
    image: "docker-node-mongo-todo-app"
    build: .
    command: "npm start"
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
    networks:
      - "project"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  
  mongo:
    image: "mongo:4.4.6"
    ports:
      - "27017:27017"
    networks:
      - "project"
networks:
  project:
